# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'createEventWXqxSe.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDateEdit, QFrame, QGroupBox,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QPushButton, QScrollArea, QSizePolicy, QSpinBox,
    QStatusBar, QTimeEdit, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 600)
        palette = QPalette()
        brush = QBrush(QColor(85, 170, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush)
        palette.setBrush(QPalette.Active, QPalette.Window, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush)
        MainWindow.setPalette(palette)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.scrollArea = QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(10, 10, 782, 531))
        palette1 = QPalette()
        brush1 = QBrush(QColor(255, 255, 255, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush1)
        brush2 = QBrush(QColor(83, 83, 83, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush1)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush2)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush2)
        self.scrollArea.setPalette(palette1)
        self.scrollArea.setAutoFillBackground(True)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 780, 529))
        self.verticalLayout_2 = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.nameInput = QLineEdit(self.scrollAreaWidgetContents)
        self.nameInput.setObjectName(u"nameInput")
        self.nameInput.setMinimumSize(QSize(0, 50))
        palette2 = QPalette()
        brush3 = QBrush(QColor(255, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush3)
        brush4 = QBrush(QColor(255, 0, 0, 128))
        brush4.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush4)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush3)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush4)
#endif
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush4)
#endif
        self.nameInput.setPalette(palette2)
        font = QFont()
        font.setFamilies([u"MV Boli"])
        font.setPointSize(24)
        font.setBold(True)
        font.setKerning(True)
        self.nameInput.setFont(font)
        self.nameInput.setAcceptDrops(True)
        self.nameInput.setFrame(False)
        self.nameInput.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout_2.addWidget(self.nameInput)

        self.line = QFrame(self.scrollAreaWidgetContents)
        self.line.setObjectName(u"line")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)

        self.verticalLayout_2.addWidget(self.line)

        self.groupBox = QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName(u"groupBox")
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QSize(0, 50))
        self.groupBox.setBaseSize(QSize(100, 100))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 0, 91, 50))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy1)
        self.label_5.setMinimumSize(QSize(0, 50))
        self.dateInput = QDateEdit(self.groupBox)
        self.dateInput.setObjectName(u"dateInput")
        self.dateInput.setGeometry(QRect(450, 20, 291, 23))
        palette3 = QPalette()
        brush5 = QBrush(QColor(54, 54, 54, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush5)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush5)
        self.dateInput.setPalette(palette3)
        self.dateInput.setAutoFillBackground(True)

        self.verticalLayout_2.addWidget(self.groupBox)

        self.groupBox_2 = QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName(u"groupBox_2")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy2)
        self.groupBox_2.setMinimumSize(QSize(0, 50))
        self.groupBox_2.setBaseSize(QSize(100, 100))
        self.label_6 = QLabel(self.groupBox_2)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 0, 261, 50))
        sizePolicy1.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy1)
        self.label_6.setMinimumSize(QSize(0, 50))
        self.timeStart = QTimeEdit(self.groupBox_2)
        self.timeStart.setObjectName(u"timeStart")
        self.timeStart.setGeometry(QRect(450, 20, 118, 23))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.Base, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        self.timeStart.setPalette(palette4)
        self.label = QLabel(self.groupBox_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(560, 20, 51, 31))
        palette5 = QPalette()
        brush6 = QBrush(QColor(0, 0, 0, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        self.label.setPalette(palette5)
        self.timeEnd = QTimeEdit(self.groupBox_2)
        self.timeEnd.setObjectName(u"timeEnd")
        self.timeEnd.setGeometry(QRect(600, 20, 118, 23))
        palette6 = QPalette()
        brush7 = QBrush(QColor(80, 80, 80, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush7)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush7)
        self.timeEnd.setPalette(palette6)

        self.verticalLayout_2.addWidget(self.groupBox_2)

        self.groupBox_3 = QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName(u"groupBox_3")
        sizePolicy2.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy2)
        self.groupBox_3.setMinimumSize(QSize(0, 50))
        self.groupBox_3.setBaseSize(QSize(100, 100))
        self.budgetLabel = QLabel(self.groupBox_3)
        self.budgetLabel.setObjectName(u"budgetLabel")
        self.budgetLabel.setGeometry(QRect(20, 0, 261, 50))
        sizePolicy1.setHeightForWidth(self.budgetLabel.sizePolicy().hasHeightForWidth())
        self.budgetLabel.setSizePolicy(sizePolicy1)
        self.budgetLabel.setMinimumSize(QSize(0, 50))
        self.budgetInput = QSpinBox(self.groupBox_3)
        self.budgetInput.setObjectName(u"budgetInput")
        self.budgetInput.setGeometry(QRect(450, 10, 291, 23))
        sizePolicy1.setHeightForWidth(self.budgetInput.sizePolicy().hasHeightForWidth())
        self.budgetInput.setSizePolicy(sizePolicy1)
        palette7 = QPalette()
        brush8 = QBrush(QColor(65, 65, 65, 255))
        brush8.setStyle(Qt.SolidPattern)
        palette7.setBrush(QPalette.Active, QPalette.Base, brush8)
        palette7.setBrush(QPalette.Inactive, QPalette.Base, brush8)
        self.budgetInput.setPalette(palette7)
        self.budgetInput.setAutoFillBackground(True)
        self.budgetInput.setMaximum(999999999)

        self.verticalLayout_2.addWidget(self.groupBox_3)

        self.groupBox_10 = QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_10.setObjectName(u"groupBox_10")
        sizePolicy2.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy2)
        self.groupBox_10.setMinimumSize(QSize(0, 50))
        self.groupBox_10.setBaseSize(QSize(100, 100))
        self.label_14 = QLabel(self.groupBox_10)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(20, 0, 281, 50))
        sizePolicy1.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy1)
        self.label_14.setMinimumSize(QSize(0, 50))
        self.lineEdit_2 = QLineEdit(self.groupBox_10)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(452, 20, 301, 21))
        palette8 = QPalette()
        brush9 = QBrush(QColor(75, 75, 75, 255))
        brush9.setStyle(Qt.SolidPattern)
        palette8.setBrush(QPalette.Active, QPalette.Base, brush9)
        palette8.setBrush(QPalette.Inactive, QPalette.Base, brush9)
        self.lineEdit_2.setPalette(palette8)

        self.verticalLayout_2.addWidget(self.groupBox_10)

        self.inviteList = QGroupBox(self.scrollAreaWidgetContents)
        self.inviteList.setObjectName(u"inviteList")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.inviteList.sizePolicy().hasHeightForWidth())
        self.inviteList.setSizePolicy(sizePolicy3)
        self.pushButton = QPushButton(self.inviteList)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 20, 121, 24))
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet(u"QPushButton {\n"
"border: 10;\n"
"border-radius: 11;\n"
"border-color: grey;\n"
"color: white;\n"
"font: 16pt \"MV Boli\";\n"
"background: rgb(0, 170, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: rgb(0, 0, 127);\n"
"}")

        self.verticalLayout_2.addWidget(self.inviteList)

        self.groupBox_11 = QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_11.setObjectName(u"groupBox_11")
        sizePolicy2.setHeightForWidth(self.groupBox_11.sizePolicy().hasHeightForWidth())
        self.groupBox_11.setSizePolicy(sizePolicy2)
        self.groupBox_11.setMinimumSize(QSize(0, 50))
        self.submitButton = QPushButton(self.groupBox_11)
        self.submitButton.setObjectName(u"submitButton")
        self.submitButton.setEnabled(True)
        self.submitButton.setGeometry(QRect(260, 20, 241, 24))
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.WindowText, brush6)
        brush10 = QBrush(QColor(0, 170, 255, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette9.setBrush(QPalette.Active, QPalette.Button, brush10)
        brush11 = QBrush(QColor(127, 255, 127, 255))
        brush11.setStyle(Qt.SolidPattern)
        palette9.setBrush(QPalette.Active, QPalette.Light, brush11)
        brush12 = QBrush(QColor(63, 255, 63, 255))
        brush12.setStyle(Qt.SolidPattern)
        palette9.setBrush(QPalette.Active, QPalette.Midlight, brush12)
        brush13 = QBrush(QColor(0, 127, 0, 255))
        brush13.setStyle(Qt.SolidPattern)
        palette9.setBrush(QPalette.Active, QPalette.Dark, brush13)
        brush14 = QBrush(QColor(0, 170, 0, 255))
        brush14.setStyle(Qt.SolidPattern)
        palette9.setBrush(QPalette.Active, QPalette.Mid, brush14)
        palette9.setBrush(QPalette.Active, QPalette.Text, brush6)
        palette9.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        palette9.setBrush(QPalette.Active, QPalette.ButtonText, brush6)
        palette9.setBrush(QPalette.Active, QPalette.Base, brush10)
        palette9.setBrush(QPalette.Active, QPalette.Window, brush10)
        palette9.setBrush(QPalette.Active, QPalette.Shadow, brush6)
        palette9.setBrush(QPalette.Active, QPalette.AlternateBase, brush11)
        brush15 = QBrush(QColor(255, 255, 220, 255))
        brush15.setStyle(Qt.SolidPattern)
        palette9.setBrush(QPalette.Active, QPalette.ToolTipBase, brush15)
        palette9.setBrush(QPalette.Active, QPalette.ToolTipText, brush6)
        brush16 = QBrush(QColor(0, 0, 0, 127))
        brush16.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Active, QPalette.PlaceholderText, brush16)
#endif
        palette9.setBrush(QPalette.Active, QPalette.Accent, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.WindowText, brush6)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush10)
        palette9.setBrush(QPalette.Inactive, QPalette.Light, brush11)
        palette9.setBrush(QPalette.Inactive, QPalette.Midlight, brush12)
        palette9.setBrush(QPalette.Inactive, QPalette.Dark, brush13)
        palette9.setBrush(QPalette.Inactive, QPalette.Mid, brush14)
        palette9.setBrush(QPalette.Inactive, QPalette.Text, brush6)
        palette9.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette9.setBrush(QPalette.Inactive, QPalette.ButtonText, brush6)
        palette9.setBrush(QPalette.Inactive, QPalette.Base, brush10)
        palette9.setBrush(QPalette.Inactive, QPalette.Window, brush10)
        palette9.setBrush(QPalette.Inactive, QPalette.Shadow, brush6)
        palette9.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush11)
        palette9.setBrush(QPalette.Inactive, QPalette.ToolTipBase, brush15)
        palette9.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush6)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush16)
#endif
        palette9.setBrush(QPalette.Inactive, QPalette.Accent, brush1)
        palette9.setBrush(QPalette.Disabled, QPalette.WindowText, brush13)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush10)
        palette9.setBrush(QPalette.Disabled, QPalette.Light, brush11)
        palette9.setBrush(QPalette.Disabled, QPalette.Midlight, brush12)
        palette9.setBrush(QPalette.Disabled, QPalette.Dark, brush13)
        palette9.setBrush(QPalette.Disabled, QPalette.Mid, brush14)
        palette9.setBrush(QPalette.Disabled, QPalette.Text, brush13)
        palette9.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        brush17 = QBrush(QColor(255, 255, 255, 135))
        brush17.setStyle(Qt.SolidPattern)
        palette9.setBrush(QPalette.Disabled, QPalette.ButtonText, brush17)
        palette9.setBrush(QPalette.Disabled, QPalette.Base, brush10)
        palette9.setBrush(QPalette.Disabled, QPalette.Window, brush10)
        palette9.setBrush(QPalette.Disabled, QPalette.Shadow, brush6)
        brush18 = QBrush(QColor(0, 255, 0, 255))
        brush18.setStyle(Qt.SolidPattern)
        palette9.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush18)
        palette9.setBrush(QPalette.Disabled, QPalette.ToolTipBase, brush15)
        palette9.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush6)
        brush19 = QBrush(QColor(0, 127, 0, 127))
        brush19.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette9.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush19)
#endif
        brush20 = QBrush(QColor(76, 255, 76, 255))
        brush20.setStyle(Qt.SolidPattern)
        palette9.setBrush(QPalette.Disabled, QPalette.Accent, brush20)
        self.submitButton.setPalette(palette9)
        self.submitButton.setAutoFillBackground(False)
        self.submitButton.setStyleSheet(u"QPushButton {\n"
"border: 10;\n"
"border-radius: 10;\n"
"border-color: grey;\n"
"color: red;\n"
"font: 16pt \"MV Boli\";\n"
"background: rgb(0, 170, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: rgb(0, 0, 127);\n"
"}")

        self.verticalLayout_2.addWidget(self.groupBox_11, 0, Qt.AlignmentFlag.Qt.AlignmentFlag.AlignVCenter)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.nameInput.setText("")
        self.nameInput.setPlaceholderText(QCoreApplication.translate("MainWindow", u"My New Event", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"GroupBox", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-weight:700; color:#000000;\">Day</span></p></body></html>", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"GroupBox", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-weight:700; color:#000000;\">Time</span></p></body></html>", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#000000;\">To</span></p></body></html>", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"GroupBox", None))
        self.budgetLabel.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-weight:700; color:#000000;\">Budget</span></p></body></html>", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("MainWindow", u"GroupBox", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-size:18pt; font-weight:700; color:#000000;\">Invites</span></p></body></html>", None))
        self.lineEdit_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"username", None))
        self.inviteList.setTitle(QCoreApplication.translate("MainWindow", u"Invites", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"smhavens", None))
        self.groupBox_11.setTitle(QCoreApplication.translate("MainWindow", u"GroupBox", None))
        self.submitButton.setText(QCoreApplication.translate("MainWindow", u"Submit", None))
    # retranslateUi

